# Leave empty, otherwise it won't work with cusotm domains.
# Github will automatically fill in the correct string.
# Still, make sure to use {{ site.baseurl }} when using absolute paths.
baseurl: ""

title: "ITC 36"
conference-number: "36th"
conference-name: "ITC 36"
conference-subname: "Towards Sustainable Digital Infrastructures"
conference-date: "02. - 06. June 2025"
conference-location: "Trondheim"
conference-location-detail: "Norwegian University of Science and Technology, Norway"
conference-domain: "https://itc36.itc-conference.org"
conference-mail: "itc36_oc@iik.ntnu.no"

# news pagination
paginate: 10
paginate_path: "/news/page:num/"

defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"

exclude: [ "Gemfile", "Gemfile.lock", "README.md" ]
theme: null
plugins:
    - jekyll-seo-tag

# deployment
host: 127.0.0.1
port: 4000
